Replaced a depenency jetty-ajp that was needed by restlet at runtime, this seems to be causing an error for people when starting the app up: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/mortbay/jetty/ajp/Ajp13SocketConnector